language: python

python:
  - "3.6"

# command to run tests
script:
  - cp -r website build
  - python3 build.py build

deploy:
  provider: s3
  bucket: "prf.afakeman.ru"
  skip_cleanup: true
  local_dir: build
  endpoint: "https://storage.yandexcloud.net"
