language: python

python:
  - "3.6"

# command to run tests
script:
  - cp -r website build
  - python3 build.py build

deploy:
  provider: firebase
  skip_cleanup: true
  token: "$FIREBASE_TOKEN"
  project: "prf-website"
